apiVersion: v1
data:
  mc: |
    image: "quay.io/minio/aistor/mc:RELEASE.2026-02-07T19-37-38Z"
kind: ConfigMap
metadata:
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-02-09T03-12-43Z
  name: adminjob-operator
