apiVersion: v1
data:
  kes: |
    image: "quay.io/minio/aistor/kes:RELEASE.2025-12-30T19-30-40Z"
  kes-sidecar: |
    image: "quay.io/minio/aistor/kes-sidecar:RELEASE.2026-02-09T03-08-34Z"
  minio: |
    image: "quay.io/minio/aistor/minio:RELEASE.2026-02-07T07-43-34Z"
  minio-sidecar: |
    image: "quay.io/minio/aistor/minio-sidecar:RELEASE.2026-02-09T03-10-35Z"
kind: ConfigMap
metadata:
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-02-09T03-12-43Z
  name: object-store-operator-default
