---
merge: true
catalog_templates:
  - template_name: catalog.yaml
    channels: stable-v1.28
    replaces: cloud-native-postgresql.v1.28.0
  - template_name: catalog.yaml
    channels: fast
    replaces: cloud-native-postgresql.v1.28.0
  - template_name: catalog.yaml
    channels: stable
    replaces: cloud-native-postgresql.v1.28.0
