apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins2tekton-operator-controller-manager
  labels:
    app.kubernetes.io/name: jenkins2tekton-operator
    app.kubernetes.io/component: controller-manager
subjects:
  - kind: ServiceAccount
    name: jenkins2tekton-operator-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins2tekton-operator-controller-manager
