apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: edb-hcp-operator
    control-plane: edb-hcp-operator
  name: edb-hcp-operator-postflight-viewer-role
rules:
- apiGroups:
  - edbpgai.edb.com
  resources:
  - postflights
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edbpgai.edb.com
  resources:
  - postflights/status
  verbs:
  - get
