apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: edb-hcp-operator
    control-plane: edb-hcp-operator
  name: postflights.edbpgai.edb.com
spec:
  group: edbpgai.edb.com
  names:
    kind: Postflight
    listKind: PostflightList
    plural: postflights
    singular: postflight
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .status.lastTransitionTime
      name: Last Check
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Postflight is the Schema for the postflights API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of Postflight
            properties:
              hm:
                description: HM is the reference to the Hybrid Management resource.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              interval:
                description: Interval defines how often to run the postflight checks.
                type: string
            type: object
          status:
            description: status defines the observed state of Postflight
            properties:
              checkResults:
                description: CheckResults is the list of postflight check results.
                items:
                  description: PostflightCheckResult defines the result of a postflight
                    check.
                  properties:
                    description:
                      description: Description is the description of the postflight
                        check.
                      type: string
                    messages:
                      description: Messages provides additional information about
                        the postflight check result.
                      items:
                        type: string
                      type: array
                    name:
                      description: Name is the name of the postflight check.
                      type: string
                    state:
                      description: State is the state of the postflight check.
                      type: string
                  type: object
                type: array
              lastTransitionTime:
                description: LastCheckTime is the timestamp of the last completed
                  postflight check.
                format: date-time
                type: string
              phase:
                description: Phase indicates the current phase of the postflight checks.
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
